# Generated by Django 5.2.7 on 2025-12-31 10:38

from django.db import migrations

def create_groups(apps, schema_editor):
    # Получаем модели из исторического контекста миграций
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Post = apps.get_model('news', 'Post')

    # Создаем группы, если их нет
    authors_group, _ = Group.objects.get_or_create(name='authors')
    common_group, _ = Group.objects.get_or_create(name='common')

    # Находим права для модели Post и отдаем их авторам
    content_type = ContentType.objects.get_for_model(Post)
    permissions = Permission.objects.filter(
        content_type=content_type,
        codename__in=['add_post', 'change_post', 'view_post']
    )
    authors_group.permissions.set(permissions)

class Migration(migrations.Migration):
    dependencies = [
        ('news', '0005_alter_category_options_alter_category_subscribers'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]